Fix broken managed identity links
MicrosoftDocs/entra-docs pull request #1100
Opened 2024-08-21 20:49 UTC by jkatz35

Reroutes links to how to guides for managed identity resource assignment to the new correct location

2024-08-21 21:53 UTC, Jak-MS commented
@barclayn 
Can you review the proposed changes? 

Note: the links will need to be fixed before we can merge it. 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-08-22 08:33 UTC, cilwerner requested changes
.md file extensions needed

2024-08-22 08:33 UTC, cilwerner commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: how-to-configure-managed-identities-scale-sets?pivots=identity-mi-methods-azp
```suggestion
            url: how-to-configure-managed-identities-scale-sets?pivots=identity-mi-methods-azp.md
```

2024-08-22 08:33 UTC, cilwerner commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: how-to-assign-access-azure-resource?pivots=identity-mi-access-cli
```suggestion
            url: how-to-assign-access-azure-resource?pivots=identity-mi-access-cli.md
```

2024-08-22 08:33 UTC, cilwerner commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: hhow-to-assign-access-azure-resource?pivots=identity-mi-access-powershell
```suggestion
            url: hhow-to-assign-access-azure-resource?pivots=identity-mi-access-powershell.md
```

2024-08-22 16:13 UTC, barclayn approved these changes

2024-08-22 16:14 UTC, barclayn commented
#sign-off

2024-08-22 21:56 UTC, Jak-MS commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: how-to-configure-managed-identities-scale-sets?pivots=identity-mi-methods-azp.md
```suggestion
            url: how-to-configure-managed-identities-scale-sets.md?pivots=identity-mi-methods-azp
```

2024-08-22 21:57 UTC, Jak-MS commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: how-to-assign-access-azure-resource?pivots=identity-mi-access-cli.md
```suggestion
            url: how-to-assign-access-azure-resource.md?pivots=identity-mi-access-cli
```

2024-08-22 21:57 UTC, Jak-MS commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: hhow-to-assign-access-azure-resource?pivots=identity-mi-access-powershell.md
```suggestion
            url: hhow-to-assign-access-azure-resource.md?pivots=identity-mi-access-powershell
```

2024-08-22 22:22 UTC, Jak-MS commented on docs/identity/managed-identities-azure-resources/index.yml
> +            url: hhow-to-assign-access-azure-resource.md?pivots=identity-mi-access-powershell
```suggestion
            url: how-to-assign-access-azure-resource.md?pivots=identity-mi-access-powershell
```

2024-08-22 23:11 UTC, merged