Update tutorial-web-app-dotnet-sign-in-users.md
MicrosoftDocs/entra-docs pull request #249
Opened 2024-01-25 01:30 UTC by faulycoelho

add missing package Microsoft.Identity.Web.DownstreamApi

2024-01-25 16:14 UTC, Court72 commented
@cilwerner

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-02-02 09:05 UTC, cilwerner requested changes
A minor modification from me. Thanks

2024-02-02 09:05 UTC, cilwerner commented on docs/identity-platform/tutorial-web-app-dotnet-sign-in-users.md
> +1. With the **Browse** tab selected, search for and select **Microsoft.Identity.Web.DownstreamApi**. Select the **Project** checkbox, and then select **Install**.
```suggestion
1. With the **Browse** tab selected, search for and select **Microsoft.Identity.Web.UI**. Select the **Project** checkbox, and then select **Install**. Repeat this for **Microsoft.Identity.Web.DownstreamApi**.
```

2024-02-02 15:31 UTC, Court72 commented
Thanks @cilwerner! I committed your suggestion.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

2024-02-06 09:13 UTC, cilwerner commented
#sign-off

2024-02-06 15:01 UTC, merged