Added Question and Answer to the Q&A - Please confirm with the P
MicrosoftDocs/entra-docs pull request #405
Opened 2024-02-19 17:05 UTC by Kenneth-Lindgren

It is a common request to avoid having the guest/b2b accounts added in the host tenant, to help our customers I have added this Q/A questions, to make it clear. 
Please ask PG to review to ensure it does not conflict with any new functionality.  
If this is possible by new functionality, please add this as a clear point in to documentation to avoid confusion. 
Thanks.

2024-02-19 17:20 UTC, Court72 commented
@msmimart

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-05-28 19:47 UTC, msmimart commented
Hi @Kenneth-Lindgren, thank you so much for your suggestion, and apologies for the long delay. Please see the suggested edits; if you'd like to make these changes we can go ahead and sign off. Thanks again!

2024-05-28 19:48 UTC, msmimart requested changes

2024-05-28 19:48 UTC, msmimart commented on docs/external-id/direct-federation.md
> +**Can we avoid the creation of guest/B2B accounts on our tenant?**
```suggestion
**Does federation eliminate the need to create a guest account in my directory for the B2B collaboration user?**
```

2024-05-28 19:48 UTC, msmimart commented on docs/external-id/direct-federation.md
> +Guests accounts will always be need to be created on the teant in order to grant access to applications, roles or membership to security groups or teams in the teanat, regardless of the federation me
No. A guest account is created for a B2B collaboration user in your directory regardless of the authentication or federation method used. This user object allows you to grant access to applications, assign roles, and define membership in security groups and teams.

2024-05-28 19:49 UTC, msmimart requested changes

2024-05-28 19:49 UTC, msmimart commented on docs/external-id/direct-federation.md
> +Guests accounts will always be need to be created on the teant in order to grant access to applications, roles or membership to security groups or teams in the teanat, regardless of the federation me
```suggestion
No. A guest account is created for a B2B collaboration user in your directory regardless of the authentication or federation method used. This user object allows you to grant access to applications, assign roles, and define membership in security groups and teams.  
```

2024-05-31 14:54 UTC, Court72 commented
@msmimart - I committed your requested changes. Add a `#sign-off` comment if these changes are ready to merge. Thanks!

2024-05-31 18:07 UTC, msmimart commented
#sign-off

2024-05-31 22:29 UTC, merged