Update msal-shared-devices.md
MicrosoftDocs/entra-docs pull request #410
Opened 2024-02-20 16:43 UTC by bgavrilMS

2024-02-20 16:43 UTC, bgavrilMS commented
CC @localden

2024-02-20 22:27 UTC, Jak-MS commented
@henrymbuguakiarie 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-02-23 19:18 UTC, localden requested changes

2024-02-23 19:18 UTC, localden commented on docs/identity-platform/msal-shared-devices.md
> +We support iOS and Android platforms for shared device mode. MAUI apps do not support shared device mode - see [2910](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/291
```suggestion
We support iOS and Android platforms for shared device mode. .NET Multi-platform App UI (MAUI) applications do not support shared device mode. For additional details about the future of this capability, see [issue #2910](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2910) on GitHub.
```

2024-02-23 19:18 UTC, localden commented on docs/identity-platform/msal-shared-devices.md
> +We support iOS and Android platforms for shared device mode. MAUI apps do not support shared device mode - see [2910](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/291
@bgavrilMS - minor adjustment to the verbiage.

2025-02-21 10:33 UTC, henrymbuguakiarie approved these changes
Hello @bgavrilMS,

LGTM but the PR has merge conflicts.

2025-02-21 15:41 UTC, closed without merging