Updating the script with a working version
MicrosoftDocs/entra-docs pull request #985
Opened 2024-07-09 14:35 UTC by franciscopgomes

Creating this PR in the correct repo (entra-docs) instead of azure-docs.

2024-07-09 21:33 UTC, Jak-MS commented
@cilwerner 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-07-10 11:38 UTC, cilwerner requested changes
A few minor changes and clarifications needed here.

2024-07-10 11:38 UTC, cilwerner commented on docs/identity-platform/jwt-claims-customization.md
> +$appObjId = "384bd956-daaa-4ac3-b558-a1e5ceb15bd2" # Replace with the Object ID of the App Registration
Is it the Application (client) id or the Object ID here? They are two different things. Is the tenant ID a GUID, or a domain?

Replacing GUIDs/values as they are sensitive info

```suggestion
$tenantId   = "aaaabbbb-0000-cccc-1111-dddd2222eeee" # Replace with your Tenant ID
$appObjId = "aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb" # Replace with the Object ID of the App Registration
```

2024-07-10 11:38 UTC, cilwerner commented on docs/identity-platform/jwt-claims-customization.md
> +# Check PowerShell version 5.1 (.Net) or PowerShell Core (.Net Core) and read the certificate file accordingly
```suggestion
# Check PowerShell version (minimum 5.1) (.Net) or PowerShell Core (.Net Core) and read the certificate file accordingly
```

2024-07-11 13:57 UTC, cilwerner commented
@franciscopgomes, please fix the recommended suggestions. Thanks

2024-07-11 14:31 UTC, franciscopgomes commented
> @franciscopgomes, please fix the recommended suggestions. Thanks

@cliwerner - the Object ID was actually a random guid generated for sample purposes (and yes, we need the Object ID of the App Reg and not the App ID here). Tenant ID will take either a verified domain or the Tenant ID GUID. I commited the suggested changes.

2024-07-15 08:36 UTC, cilwerner approved these changes
Looks good now @franciscopgomes.

2024-07-15 08:36 UTC, cilwerner commented
#sign-off

2024-07-15 14:17 UTC, merged